# QA Agent Prompts — per-sub-agent prompt templates
#
# Backward-compat: re-exports old prompt names from new sub-modules.

from .router import SYSTEM_PROMPT, ROUTER_PROMPT
from .solver import THINK_PROMPT, SYNTHESIS_PROMPT

# Legacy aliases for backward compatibility
SIMPLE_CLASSIFY_PROMPT = ROUTER_PROMPT
ANSWERER_THINK_RAG_PROMPT = THINK_PROMPT
ANSWERER_THINK_WEB_PROMPT = THINK_PROMPT
ANSWERER_SYNTHESIS_PROMPT = SYNTHESIS_PROMPT
from .reflector import REFLECT_PROMPT as REVIEWER_PROMPT
REVIEWER_PROMPT = REVIEWER_PROMPT  # avoid F401

__all__ = [
    "SYSTEM_PROMPT", "ROUTER_PROMPT",
    "THINK_PROMPT", "SYNTHESIS_PROMPT",
    "REVIEWER_PROMPT", "REFLECT_PROMPT",
    "SIMPLE_CLASSIFY_PROMPT",
    "ANSWERER_THINK_RAG_PROMPT", "ANSWERER_THINK_WEB_PROMPT",
    "ANSWERER_SYNTHESIS_PROMPT",
]
